name: post_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.ÃŸÃŸÃŸZZZZÃS43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.1.0+5

environment:
  sdk: ">=3.0.0-91.0.dev <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  acronym: ^0.5.1
  automatic_animated_list: ^1.1.0
  awesome_notifications: ^0.10.1
  bot_toast: ^4.1.3
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.8
  cloud_functions: ^5.5.1
  cupertino_icons: ^1.0.2
  dropdown_search: ^6.0.2
  file_picker: ^10.1.9
  file_saver: ^0.2.14
  firebase_app_check: ^0.3.2+6
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  firebase_messaging: ^15.2.6
  firebase_storage: ^12.4.6
  floating_action_bubble: ^1.1.4
  flutter:
    sdk: flutter
  flutter_animate: ^4.1.1+1
  flutter_highlight_text: ^0.0.4
  flutter_localizations:
    sdk: flutter
  flutter_overlay_window: ^0.5.0
  flutter_screenutil: ^5.8.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  flutter_typeahead: ^5.2.0
  fluttertoast: ^8.0.9
  gal: ^2.3.1
  get: ^4.6.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.4.0
  image_picker: ^1.0.7
  internet_connection_checker: ^3.0.1
  intl: any
  lottie: any
  mime: ^2.0.0
  modal_progress_hud_nsn: ^0.5.1
  open_file: ^3.3.2
  path_provider: ^2.1.0
  pro_image_editor: ^9.9.2
  provider: ^6.0.3
  shared_preferences: ^2.0.10
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^29.2.7
  table_calendar: ^3.0.9
  timezone: ^0.10.1
  url_launcher: ^6.1.14
  uuid: ^4.2.2
  vibration: ^3.1.3

dev_dependencies:
  build_runner: ^2.2.1
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.14.3

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.4
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/post-logo-fix.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"
  # image: "images/post_app_icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - logo/
    - font/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: font/Roboto-Regular.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
